AWSTemplateFormatVersion: "2010-09-09"

Description: ECR Repositories

Resources:
  CodebuildRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: docker-in-aws/codebuild
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: CodeBuildAccess
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
  TodobackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: docker-in-aws/todobackend
      